name=ESP_H264_Arduino
version=1.0.0
author=Espressif (adapted)
maintainer=You <you@example.com>
sentence=H.264 encoder/decoder adapted for Arduino-ESP32-S3 (software only)
paragraph=This is a trimmed Arduino library of Espressif's esp_h264 component. Hardware-specific code is omitted. Precompiled SW libraries are in src/esp32s3/ folder.
category=Video
url=https://github.com/espressif/esp-h264-component
architectures=esp32
precompiled=true
ldflags=-lopenh264 -ltinyh264