name=codec-h264 for ESP32-S3
version=0.1.0
author=Espressif (adapted)
maintainer=Phil Schatzmann
sentence=H.264 encoder/decoder adapted for Arduino-ESP32-S3 (software only)
paragraph=This is a trimmed Arduino library of Espressif's esp_h264 component. Hardware-specific code is omitted. Precompiled SW libraries are in src/esp32s3/ folder.
category=Video
url=https://github.com/pschatzmann/codec-h264-ESP32S3
architectures=esp32
precompiled=true
ldflags=-lopenh264 -ltinyh264